[gcp_service_account]  # Esta é a seção principal que você vai referenciar no código
type = "service_account"
project_id = "dashboard-mentoria-465319"
private_key_id = "1046db5b960273748fb3ce6ae7216854bd65a583"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrZslyOIMf0FJo
8ggvSblCIJX8z5VzKPGkg89lzBL4zk9QwAvMmhMbgXbcUlYoaxuZLGoFpJMWb9TK
zyJriwWfswpHceR6mmcJ+qmeOnqmaERxa3uQ34DS6yQ3/4i9Rgx8xZ0UbN7f5jUN
JXEi2vE9hNYKNdRDuDqPP+86fwTuMhRhWNhxbp3OTa6nzTWKN3aBQEcHyVRgeEZ3
fY33Oo0GCwqxiWYTI7xQCa3OgLzbtY+qM/VEHU1RDDkZbAtvu/yZKQMOJPaLoRpu
ZiWOG5FlzkkWC4fWuerSkjg6I/1Lyzt401ZKFm1o0aW86NFtB1G2DZ4a6ZLj32U+
SIfj96bLAgMBAAECggEACUOPYAjlnEK5L0F2wu1AuMmIqKASdso7TUFvrYGNczzd
pyc3zlPhhn/FjCDujJ6zF064zNK0vZ1HKpeSkNLhwMoRyN8MSZXTFwRFtBN7Edn+
19+iBjqnaj71ScD1g7+nn7LIS6a/TsU+ojqM1iS5QFb0XFJXoMw7SFA4dW9aEQLH
oQXz6CFaCUO20C90KhzC9298vBvL2n+Y1qHW31avUU+8xwlLojo8i6NArlo4FZAQ
9FjTYRYsNuB1o9k8/l3DHCxSj1L7w1JsV5Ap8K9IZolrDssRZjePXJKg51gl4Ar2
gqg4RkQ0cnY0xT2vrfcsiBiVIj69q4kq4mt58qR/qQKBgQDwWVFfkoSKBNR6Xmsv
ArhN2fXOjGwHd7RHC5camdx5stuWS50nr0uQBDsZAeT/hk4F+dauUnXwX8USB7uK
S6AVWqiCl6sy/xI3hAvuPi2/s463TKp3uOvtmIHty8gnXyeO960+iSfdVMRkbOZz
JGO8geLr3hGVwNRLRxWC1RBZ7QKBgQC2kBjfz9zsBgPBbprL0tn4BTkNCqx2XLMc
/C3+vBuMLOXFfnrciU/KUvyjHfv3AJY4NTJbTNpYWtHOc254EDM2guHE46PsaaMT
IfHzxNb0RBZCQtmcMPBuhSKNNoTsGSkhuikSPHEww7WsxTEvoZDJd+YNNdzreNe8
oSiQthmMlwKBgENjV5xrUTv9ZLG2nWi943z4eqHh3zwsxOASkNhFgXqhuk2mf7ar
wIztksBNNq6qMmAcj6OqvSSbRX7rqhp5X7X9CDgtXDPdLndgT5QJ3Pvd1UrxdO5C
a+vfEbbhpwna9RVxviJFhGbbKIFbwzVPY6Nr63rkdZu+SAefM5nOMVp1AoGAB9sD
dv32v6EyoCwmNQcJogZ3gfwnl6A9hM3FHOTzOoDkEi9zEfJGoKoZfNtZcDNyQ1Dm
rc8MxiiCRqPo6Pmpenr/Q/2XnCCfh786LgcWSMR1QLynqHTio57O8cyaw54BixX7
lnFLXZHOS3TgvO/yzvh9yau7qdY1UkSM/k0XpFkCgYEAv7vHZfaM5eQMA2AoMkJD
tMx04OrlX5j2jObKGLN4KpGSbiu4Z5J89QxkCIobwVqQ7Ww+DztioMVx1QeY8blg
o4xSgavkmyZE7b4QrKiJF5hz3t8ysQ/IO2muL9TBk84tfR70H6wG1Ji+O9j2fHLt
hrj8xU/S8iRVGCdWjy1D2YY=
-----END PRIVATE KEY-----"""
client_email = "dashboard-mentoria-service-acc@dashboard-mentoria-465319.iam.gserviceaccount.com"
client_id = "112706855028797016856"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dashboard-mentoria-service-acc%40dashboard-mentoria-465319.iam.gserviceaccount.com"
universe_domain = "googleapis.com"